# Generated by Django 5.0.3 on 2024-05-25 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateField(auto_created=True, blank=True, null=True, verbose_name='تاریخ افزودن محصول')),
                ('name', models.CharField(blank=True, max_length=500, null=True, verbose_name='نام محصول')),
                ('price', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='قیمت محصول')),
                ('color', models.CharField(blank=True, choices=[('ابی', 'ابی'), ('سفید', 'سفید'), ('سیاه', 'سیاه'), ('قرمز', 'قرمز')], max_length=4, null=True, verbose_name='رنگ محصول')),
                ('size', models.IntegerField(blank=True, default=0, null=True, verbose_name='اندازه مصحول')),
                ('discount', models.IntegerField(blank=True, default=0, null=True, verbose_name='تخفیف محصول')),
                ('text', models.TextField(blank=True, null=True, verbose_name='توضیحات محصول')),
            ],
        ),
    ]
