# Generated by Django 5.0.3 on 2024-05-26 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_attributes_alter_product_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributes',
            name='icon_html',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='فرمت اچ تی ام ال ایکون'),
        ),
    ]
