# Generated by Django 5.0.3 on 2024-05-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_category_product_category_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='productimage', verbose_name='عکس محصول'),
        ),
    ]
