# Generated by Django 5.0.3 on 2024-06-01 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='category_image', verbose_name='عکس دسته بندی'),
        ),
    ]
