# Generated by Django 5.0.3 on 2024-06-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_color_size_remove_product_color_remove_product_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='name',
            field=models.IntegerField(verbose_name='سایز محصول'),
        ),
    ]
