# Generated by Django 5.0.7 on 2024-09-08 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_category_parent_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, to='product.category', verbose_name='دسته بندی ها '),
        ),
    ]
