# Generated by Django 5.0.3 on 2024-06-06 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_user_email_remove_user_phonenumber_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=12, null=True, unique=True, verbose_name='شماره تماس'),
        ),
    ]
