# Generated by Django 5.0.3 on 2024-06-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterUserOtp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('code', models.SmallIntegerField(verbose_name='کد تایید')),
                ('data_exprition', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربر ها ',
            },
        ),
    ]
