# Generated by Django 5.0.3 on 2024-06-08 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_registeruserotp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registeruserotp',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'ثبت نام کاربر ها '},
        ),
        migrations.AddField(
            model_name='registeruserotp',
            name='token',
            field=models.CharField(max_length=200, null=True, verbose_name='توکن کاربر'),
        ),
    ]
