# Generated by Django 5.0.3 on 2024-06-10 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_registeruserotp_options_registeruserotp_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ اضافه شدن'),
        ),
        migrations.AddField(
            model_name='user',
            name='discription',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='توضیحات کاربر'),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='user_image', verbose_name='عکس پروفایل'),
        ),
    ]
