# Generated by Django 5.0.3 on 2024-07-19 05:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_user_created_at_user_discription_user_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=12, verbose_name='شماره تماس')),
                ('fullname', models.CharField(max_length=100, verbose_name='نام شما')),
                ('address', models.CharField(max_length=100, verbose_name='ادرس')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل شما')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'اطلاعات کاربر',
                'verbose_name_plural': 'اطلاعات کاربر ها ',
            },
        ),
    ]
