# Generated by Django 5.0.3 on 2024-07-20 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_order_address_remove_order_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='قیمت محصول'),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='total',
            field=models.BigIntegerField(default=0, verbose_name='قیمت نهایی'),
        ),
    ]
