# Generated by Django 5.0.3 on 2024-07-20 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_orderitems_price_orderitems_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='tedad',
            field=models.IntegerField(default=0, verbose_name='تعداد محصول'),
        ),
    ]
