# Generated by Django 5.0.3 on 2024-07-24 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderitems_tedad'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='total_price',
            field=models.BigIntegerField(default=0, verbose_name='قیمت کل محصولات خرید کرده'),
        ),
    ]
